<?php 

define( 'DB_NAME', getenv( 'MYSQL_DATABASE' ) );
define( 'DB_USER', getenv( 'MYSQL_ADMIN' ) );
define( 'DB_PASSWORD', trim( file_get_contents( '/run/secrets/db_password' ) ) );
define( 'DB_HOST', getenv( 'WORDPRESS_DB_HOST' ) );

define( 'DB_CHARSET', 'utf8mb4' );

$table_prefix = 'wp_';

/* That's all, stop editing! Happy publishing. */

if ( ! defined( 'ABSPATH' ) ) {
	define( 'ABSPATH', __DIR__ . '/' );
}

require_once ABSPATH . 'wp-settings.php';